//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TfsPlayground.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://SkyKick.visualstudio.com/DefaultCollection")]
        public string TfsUri {
            get {
                return ((string)(this["TfsUri"]));
            }
            set {
                this["TfsUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyKick 1")]
        public string TfsSkyKickTeamProjectName {
            get {
                return ((string)(this["TfsSkyKickTeamProjectName"]));
            }
            set {
                this["TfsSkyKickTeamProjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWAT-TFS")]
        public string TfsSwatUsername {
            get {
                return ((string)(this["TfsSwatUsername"]));
            }
            set {
                this["TfsSwatUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("l7w2ez2lkjyca2ibnq3t3m7m2at5qjoyw7ijphrezlfe4z4ripbq")]
        public string TfsSwatPasskey {
            get {
                return ((string)(this["TfsSwatPasskey"]));
            }
            set {
                this["TfsSwatPasskey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DevOps 1")]
        public string TfsDevOpsTeamProjectName {
            get {
                return ((string)(this["TfsDevOpsTeamProjectName"]));
            }
            set {
                this["TfsDevOpsTeamProjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("skykick")]
        public string TfsSkyKickAccountName {
            get {
                return ((string)(this["TfsSkyKickAccountName"]));
            }
            set {
                this["TfsSkyKickAccountName"] = value;
            }
        }
    }
}
