//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmPlayground.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("trestin.bradley@skykick.com")]
        public string OverrideUsername {
            get {
                return ((string)(this["OverrideUsername"]));
            }
            set {
                this["OverrideUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tb1116940+")]
        public string OverridePassword {
            get {
                return ((string)(this["OverridePassword"]));
            }
            set {
                this["OverridePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("skykick")]
        public string CrmOrgName {
            get {
                return ((string)(this["CrmOrgName"]));
            }
            set {
                this["CrmOrgName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crm.dynamics.com")]
        public string CrmServerAddress {
            get {
                return ((string)(this["CrmServerAddress"]));
            }
            set {
                this["CrmServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc")]
        public string CrmDiscoveryUrl {
            get {
                return ((string)(this["CrmDiscoveryUrl"]));
            }
            set {
                this["CrmDiscoveryUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cloudvisors.api.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string CrmOrgServiceUrl {
            get {
                return ((string)(this["CrmOrgServiceUrl"]));
            }
            set {
                this["CrmOrgServiceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crm_plugins@skykick.com")]
        public string CrmUsername {
            get {
                return ((string)(this["CrmUsername"]));
            }
            set {
                this["CrmUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SD+uwCSUgeEu7u6BpWWWiJXvIo6GVz4zsi+WU4Qy3hQGg8abVhZiJ/2nmXiKNR6eJ66AEPSx1Wy/FK3qO9Qior3M+MhCWSotg0ND//Se6y4fS3wcFLGjfTfhcVMTrmN6mPu11euszzWGDziUgIB0uUiMHeAr9acnIBpYhgZ9TZkMlOlWGMybPVquPnmXnvi5gQ2lMGWHOKk9qey8FL92d4Kw9ZrifAA9tOBY4kQR7pFM+WTM0rnhvU9NognUdZYZHNKSUcqntLwAnFWsr/KoUfxfcVo3kSlj+k/aI1z4zmkNIh6HK30q+wM87eQPAkKw2q/qJ0E/n8S6O5Lub5Dpy8YxYYvpuwqTBUNRUSFg5EVKpiFw9V95yoJ86GPjdc4TGT/MPAEApdKetBy/2rJhlXYi5Aj8eDJfGcOPHfD9iKzU/lL0u36XSt67EAF9PqneJBlfDiu9kfBdeD3Taq7nZAeV3vZbSD/bLgxiD1J5mVxUuJ50xIbl4wo7G12TjfXikfUQeSztGnCjS6ZA2J36vRU8ePZ3ETqGmKhG8+nc0wZIX69QveVjdQScfkFZsE8/HDJoXfOc1Hn2W0uBLpdeduDTVqzyCUq/LnlcYS0Vkm46orK2Pabe4nVMjednJcst9x3Cwt6VkiOi62u50B+N9bSh/KpRBuFL6RosFXsySf+P2MN2Fv0is2JqKDk6OcZdA5MxvlRdSoqtqZVh9fpR6JG0RnKIKiNXunCl+8lT6CF4cfmN5lB3rjPNfkUSe5CrJnVYnDGD1gshfjN/jIm2qjroLbv83Y2IVDk8SSG21tlwC5Srz7vk2O3Qqmc=")]
        public string CrmPassword {
            get {
                return ((string)(this["CrmPassword"]));
            }
            set {
                this["CrmPassword"] = value;
            }
        }
    }
}
