//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmPlayground.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OverrideUsername {
            get {
                return ((string)(this["OverrideUsername"]));
            }
            set {
                this["OverrideUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OverridePassword {
            get {
                return ((string)(this["OverridePassword"]));
            }
            set {
                this["OverridePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@" -                 <value>https://cloudvisors.api.crm.dynamics.com/XRMServices/2011/Organization.svc</value>
 -                 <value>https://cloudvisors.api.crm.dynamics.com/XRMServices/2011/Organization.svc</value>
https://cloudvisors.api.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string CrmOrgServiceUrl {
            get {
                return ((string)(this["CrmOrgServiceUrl"]));
            }
            set {
                this["CrmOrgServiceUrl"] = value;
            }
        }
    }
}
